### PR TITLE
Reset application state when navigating to home page

### LINKED ISSUE #366: Codesplain does not reset when you click the logo
## Expected Behavior
If I click the logo, it should route me to the home view, with all fields cleared out

## Current Behavior
Data from the previous snippet still persists

## Steps to Reproduce (for bugs)
1. Make a new snippet, save it
2. Click the logo
3. Notice that the browser location did change, but that the data from the previous snippet persists

## Possible Solution
I believe that this is occurring because when the route changes, `App`'s state doesn't change and therefore doesn't cause a re-render

### PR DESCRIPTION
**Pull request by solkaz**
## Description
This PR properly resets the application state when the Codesplain logo is clicked so that the user is presented with a clean, new view. There is a check added before wiping any changes, so that if there are unsaved changes, the user will be asked to confirm navigation before doing so, and will reset state/redirect them if there are no unsaved changes.

## Motivation and Context
Fixes #366 

## Checklist:

- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/containers/CodesplainAppBar.jsx [hunk 1]
```diff
@@ -1,9 +1,12 @@
 import React from 'react';
 import { connect } from 'react-redux';
 import AppBar from 'material-ui/AppBar';
+import Dialog from 'material-ui/Dialog';
+import FlatButton from 'material-ui/FlatButton';
```
Comment (dane-johnson) [inline src/containers/CodesplainAppBar.jsx]: Consider doing all these imports as one with destructuring
