### PR TITLE
Fix errors and warnings in console

### LINKED ISSUE #507: The snippet list isn't being updated when deleting a snippet
## Expected Behavior
After deleting a snippet, the snippet lists should be refreshed in the browser

## Current Behavior
After deleting a snippet, that snippet is still present in the My Snippets menu, and doesn't go away until you refresh the browser

## Browser
Chrome

## Steps to Reproduce (for bugs)
1. Open a snippet
2. Delete that snippet
3. Open the `My Snippets` menu
4. See that the snippet name is still on the list

### PR DESCRIPTION
**Pull request by Hopding**
## Description

* Fixed import location of `setAuthor` in `SnippetArea`, so the user is properly redirected and their snippet lists are updated when they delete a snippet.
* Fixed the URL being used to get a user's avatar, which was resulting in a 404.
* Fixed PropType warning due to the app being rendered before `snippetKey` was set.

## Motivation and Context

Fixes #507. Nobody likes type errors, 404s, and PropType warnings.

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Browsers

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Mobile:
- [ ] Other:

### CODE REVIEW

File: src/util/requests.js [hunk 1]
```diff
@@ -43,15 +43,15 @@ export const sanitizeSnippetList = (snippetList) => {
   return snippetList;
 };
 
-export const makeUserUrl = user => `${GITHUB_API_URL}/users/${user}`;
+export const makeUserUrl = () => `${GITHUB_API_URL}/user`;
```
Comment (dane-johnson) [inline src/util/requests.js]: You can't do this because in this context `user` isn't necessarily the authenticated user, can also be the owner of the snippet.

**Comment by Hopding** [comment]
@dane-johnson That problem is fixed now as a result of pulling in master & resolving the conflicts.
