### PR TITLE
Better empty title error

### LINKED ISSUE #391: Change snackbar text to say "Snippet Name" when trying to save without a title
## Current Behavior
pasted image at 2017_04_13 03_12 pm

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

### PR DESCRIPTION
**Pull request by dane-johnson**
## Description

Changes the title error to use similar language with the rest of the project.

## Motivation and Context

Closes #391 
## Checklist:

- [x] All new and existing tests passed.

### CODE REVIEW

File: src/containers/SnippetArea.jsx [hunk 1]
```diff
@@ -130,9 +130,10 @@ export class SnippetArea extends React.Component {
 
     const { id } = router.params;
 
+    // Make sure title is populated
     if (!snippetTitle) {
       this.setState({ titleErrorText: 'This field is required' });
-      this.showSnackbar('Please populate the title field before saving.');
+      this.showSnackbar('Please enter a snippet name.');
```
Comment (thebho) [inline src/containers/SnippetArea.jsx]: Good catch
