### PR TITLE
Fix responsiveness of the RuleLabel buttons

### LINKED ISSUE #517: Windows need to be 1400w before the Filters are displayed in 2 columns
## Expected Behavior
At 1200 the filters should still be displayed in 2 columns

## Current Behavior
It varies, but usually the filters display in a single column at less than 1400 width

## Browser
Safari and Chrome

### PR DESCRIPTION
**Pull request by solkaz**
## Description
Refactors the RuleLabel buttons to use flex-box properties, making them more responsive
Also removes the padding from the Filter and Annotation titles, so there's more room for the content in their respective sections

## Motivation and Context
Fixes #517

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Browsers

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Mobile:
- [ ] Other:

### CODE REVIEW

File: src/components/RulesSelector.jsx [hunk 1]
```diff
@@ -27,19 +29,14 @@ const makeListItems = (filters, onRuleSelected) => (
 const RulesSelector = ({ filters, onRuleSelected }) => {
   const listItems = makeListItems(filters, onRuleSelected);
   return (
-    <div>
+    <div className="rule-selector-container">
```
Comment (dane-johnson) [inline src/components/RulesSelector.jsx]: We are doing styles as an object, not css files

Comment (solkaz) [inline src/components/RulesSelector.jsx]: We're using both of those methods in the project, this isn't new. Also, it's more conducive for development since you don't have to reload the app to see your changes.

Comment (dane-johnson) [inline src/components/RulesSelector.jsx]: @Hopding is this true? I've been doing all of my styling as objects

Comment (solkaz) [inline src/components/RulesSelector.jsx]: You can check in `AppBody`; both the SnippetArea and the right section use classes

Comment (Hopding) [inline src/components/RulesSelector.jsx]: My understanding is that we decided to use objects for styling. I'm not aware of any files that use CSS classes (did a quick search and didn't find any either), with the exception of `Editor.jsx`. However, the reason that component uses them is because it is required for CodeMirror styling.

**Comment by Hopding** [comment]
This is definitely a nice improvement. However you removed the padding between the filters. Was that intentional? I'd prefer to keep it.

**Comment by thebho** [comment]
It was a compromise to use dynamic sizing

File: src/components/RulesSelector.jsx (hunk 1 above)
Comment (solkaz) [inline src/components/RulesSelector.jsx]: I meant to say that the elements in AppBody are using CSS id selectors, not classes

In this case, we're not required to use CSS selectors to apply styles to the buttons, although I think it's more appropriate to do so in this case for a couple of reasons. That said, I can revert to using our previous method.

**Comment by Hopding** [comment]
Why is padding incompatible with resizing?

File: src/components/RulesSelector.jsx (hunk 1 above)
Comment (Hopding) [inline src/components/RulesSelector.jsx]: There are certain CSS selectors that don't directly translate to JavaScript object. So if its going to be complicated to use objects for certain selectors, then I'm not against keeping them. But for the sake of consistency, it would be good to try to use objects when possible.

**Comment by solkaz** [comment]
*Margin, not padding. For some reason, adding margins breaks flexbox properties.

**Comment by thebho** [comment]
Yeah, this was the best of the options i saw.  There is a slack history from yesterday if you are interested
